<div class="box ">
    <div class="title"><?php _lang('whos_online2::whos_online2') ?></div>
    <div class="box-content" style="padding-top: 0">
        <div class="row">
        <div class="container whos_online2" style="display: block">
        <?php echo view('whos_online2::online2',array('limit'=>$limit)); ?>
        </div>
        </div>
    </div>
    <a ajax="true" href="<?php echo url_to_pager('online-members') ?>" class="loop owl-carousel owl-theme ">
     <div class="owl-carousel">
    <div class="title"><?php _lang('who_online2::who_online2') ?></div>
    <div class="row">
    <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700,400italic,300italic' rel='stylesheet' type='text/css'>
      <link rel="stylesheet" href="../plugins/whosonline2/css.theme.min.css">
 
          <h4 id="center-with-loop">Center with loop</h4>
          <div class="loop owl-carousel owl-theme">
            <div class="online-members">
              <h4>1</h4>
            </div>
            <div class="online-members">
              <h4>2</h4>
            </div>
            <div class="online-members">
              <h4>3</h4>
            </div>
            <div class="online-members">
              <h4>4</h4>
            </div>
            <div class="online-members">
              <h4>5</h4>
            </div>
            <div class="online-members">
              <h4>6</h4>
            </div>
            <div class="online-members">
              <h4>7</h4>
            </div>
            <div class="online-members">
              <h4>8</h4>
            </div>
            <div class="online-members">
              <h4>9</h4>
            </div>
            <div class="online-members">
              <h4>10</h4>
            </div>
            <div class="online-members">
              <h4>11</h4>
            </div>
            <div class="online-members">
              <h4>12</h4>
            </div>
          </div>?>
            <?php _lang('more') ?>
            <i class="ion-ios-arrow-forward pull-right"></i>
        </div>
    </a>
                <script src="https://ajax.googleapis.com/ajax/libs/d3js/5.7.0/d3.min.js"></script> 
            <script src="../plugins/whosonline2/js/owl.carousel.min.js"></script>
</div>